apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: docker.io/yaoqiangpersonal/boot-k8s-demo:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: default-secret
---

apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app #选中上面的 Deployment
  ports:
    - name: http
      port: 7003 #对外7003端口
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx

---
#Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-localhost
spec:
  ingressClassName: nginx
  rules:
    - host: demo.boot.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 7003
