name: dep to 207.148.118.227

on:
  push:
    # 分支
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven
      - name: compile
        run: mvn compile
      - name: Generate the package
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      - name: deployment
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/github-action-0.0.1-SNAPSHOT.jar
          remote: actions/github-action.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: run springboot
        if: always()
        uses: appleboy/ssh-action@master
        with:
          script: | # 命令中的 & 表示在后
            cd actions && bash test.sh
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}